'use client';

import { useEffect, useState } from 'react';
import { api } from '../lib/api';

type MaritimeContext = { vessel: Record<string, any> | null; vessels: Array<Record<string, any>>; icebergs: Array<{ geometry?: { coordinates?: [number, number] }; properties?: Record<string, any> }>; route?: { mode?: string; ship?: Record<string, any>; metrics?: { distance_km?: number; travel_time_hours?: number; iceberg_risk?: number }; iceberg_routes?: { features?: unknown[] } } | null };

export default function SOSControl() {
  const [context, setContext] = useState<MaritimeContext>({ vessel: null, vessels: [], icebergs: [] });
  const [open, setOpen] = useState(false);
  const [description, setDescription] = useState('Potential navigation hazard detected. Requesting immediate maritime review.');
  const [status, setStatus] = useState('');
  useEffect(() => { const update = (event: Event) => setContext((event as CustomEvent<MaritimeContext>).detail); window.addEventListener('maritime-context', update); return () => window.removeEventListener('maritime-context', update); }, []);
  const vessel = context.vessel ?? context.vessels.find((candidate) => [candidate.vessel_id, candidate.mmsi, candidate.name].some((value) => String(value ?? '').toLowerCase() === String(context.vessel?.vessel_id ?? '').toLowerCase())) ?? context.vessels[0] ?? null;
  const hasCoordinates = vessel?.latitude != null && vessel?.longitude != null;
  const nearby = context.icebergs.filter((feature) => { const coordinates = feature.geometry?.coordinates; if (!coordinates || !hasCoordinates) return false; const distance = Math.hypot((coordinates[1] - Number(vessel.latitude)) * 111, (coordinates[0] - Number(vessel.longitude)) * 55); return distance <= 100; }).slice(0, 8);
  function generatedDescription() { const vesselName = vessel?.name ?? vessel?.vessel_id ?? vessel?.mmsi ?? 'Tracked ship'; const vesselId = vessel?.vessel_id ?? vessel?.mmsi ?? 'unavailable'; const routeMetrics = context.route?.metrics; const routeSummary = context.route ? `Route mode: ${context.route.mode ?? 'planned'}; destination: ${context.route.ship?.destination ?? 'configured destination'}; distance: ${routeMetrics?.distance_km ?? 'unavailable'} km; travel time: ${routeMetrics?.travel_time_hours ?? 'unavailable'} hours; iceberg risk: ${routeMetrics?.iceberg_risk ?? 'unavailable'}.` : 'No optimized route is currently active.'; const icebergSummary = nearby.length ? `Nearby icebergs: ${nearby.map((feature) => { const coordinates = feature.geometry?.coordinates; return `${feature.properties?.id ?? 'Unknown'} (${coordinates?.[1]?.toFixed(2) ?? 'n/a'}°, ${coordinates?.[0]?.toFixed(2) ?? 'n/a'}°)`; }).join(', ')}.` : 'No iceberg within 100 km.'; return `${vesselName} (ID: ${vesselId}) at ${Number(vessel?.latitude).toFixed(2)}°, ${Number(vessel?.longitude).toFixed(2)}°. ${routeSummary} ${icebergSummary}`; }
  async function sendAlert() { if (!vessel) { setStatus('Select or track a vessel first.'); return; } setStatus('Sending alert...'); try { const result = await api<{ status: string; detail?: string }>('/api/alerts/sos', { method: 'POST', body: JSON.stringify({ vessel: { id: vessel.vessel_id ?? vessel.mmsi ?? vessel.name, name: vessel.name, latitude: vessel.latitude, longitude: vessel.longitude }, nearby_icebergs: nearby.map((feature) => ({ id: feature.properties?.id, latitude: feature.geometry?.coordinates?.[1], longitude: feature.geometry?.coordinates?.[0] })), description }) }); setStatus(result.detail ?? 'Alert sent successfully.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Unable to send alert.'); } }
  return <><button className="sos-button" type="button" onClick={() => { setOpen(true); setStatus(''); setDescription(generatedDescription()); }} aria-label="Open emergency maritime alert">SOS <span>!</span></button>{open && <div className="sos-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setOpen(false); }}><section className="sos-dialog" role="dialog" aria-modal="true" aria-labelledby="sos-title"><button className="account-close" type="button" onClick={() => setOpen(false)} aria-label="Close SOS dialog">×</button><p className="eyebrow">Emergency maritime signal</p><h2 id="sos-title">Send SOS alert?</h2><p className="sos-location">{vessel ? `${vessel.name ?? vessel.vessel_id ?? 'Tracked ship'} · ${Number(vessel.latitude).toFixed(2)}°, ${Number(vessel.longitude).toFixed(2)}°` : 'No ship selected'}</p><p className="sos-nearby">{nearby.length} iceberg{nearby.length === 1 ? '' : 's'} within 100 km will be included.{context.route ? ` ${context.route.iceberg_routes?.features?.length ?? 0} route risk segment(s).` : ''}</p><label>Alert description<textarea value={description} onChange={(event) => setDescription(event.target.value)} /></label>{status && <p className="sos-status">{status}</p>}<button className="sos-send" type="button" onClick={sendAlert}>Send emergency email <span>→</span></button></section></div>}</>;
}
